#version: "3"

#services:

#  SonarQube:
#    image: sonarqube:community  # Correction du nom de l'image
#    depends_on:
#      - db
#    environment:
#      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonartest
#      SONAR_JDBC_USERNAME: sonartest
#      SONAR_JDBC_PASSWORD: sonartest
#    volumes:
#      - SonarQube_data:/opt/sonarqube/data  # Mise à jour du chemin du volume
#      - SonarQube_extensions:/opt/sonarqube/extensions  # Mise à jour du chemin du volume
#      - SonarQube_logs:/opt/sonarqube/logs  # Mise à jour du chemin du volume
#    ports:
#      - "9000:9000"

#  db:
#    image: postgres:12
#    environment:
#      POSTGRES_DB: sonartest
#      POSTGRES_USER: sonartest
#      POSTGRES_PASSWORD: sonartest  # Correction du mot de passe
#    volumes:
#      - postgresql:/var/lib/postgresql
#      - postgresql_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#volumes:
#  SonarQube_data:
#  SonarQube_extensions:
#  SonarQube_logs:
#  postgresql:
#  postgresql_data:
version: "3"

services:
  sonarqube:
    image: sonarqube:7.9.5-community
    depends_on:
      - init
    environment:
      SONARQUBE_JDBC_URL: dbc:sqlserver://192.168.2.10;databaseName=sonartest
      SONAR_JDBC_USERNAME: sonartest
      SONAR_JDBC_PASSWORD: sonartest
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ulimits:
      nproc: 131072
      nofile:
        soft: 8192
        hard: 131072
    ports:
      - "9000:9000"
  init:
    image: bash
    privileged: true
    user: root
    volumes:
      - $(pwd)/init.sh:/mnt/init.sh <---- replace the path
    command: ["sh", "-e", "/mnt/init.sh"]
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp: